### ISSUE TITLE
Stats thread terminated

### ISSUE THREAD

**Issue by neo3k** [DefGuard/gateway#106]
I have defguard deployed in ECS. I was doing QA testing, specifically testing connecting to the VPN with revoked access. The stats thread stopped working.

`[2024-07-03T12:58:58Z ERROR defguard_gateway::gateway] Stats thread terminated with error: status: Internal, message: "Device with public key B6hi+eJvldxm8lVbCvmc23e5j7Ae/NwrFs+LTe0mNm4= not found", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 03 Jul 2024 12:58:58 GMT", "content-length": "0"} }`

**Comment by teon** [comment]
@neo3k we have reelased a 0.7.1 that should fix this problem. If it doesn't please re-open and post some logs.
