### ISSUE TITLE
Instaling new gateway packages doesn't restart gateway

### ISSUE THREAD

**Issue by teon** [DefGuard/gateway#128]
Add to post-install to restart gateway service

**Comment by prabakaran-yorosis** [comment]
> Add to post-install to restart gateway service

Gateway: h2 protocol error: http2 error


Hi ,

We are facing the below issue, while create the gateway in another VM.

ERROR defguard_gateway::gateway] Couldn't retrieve gateway configuration from the core. Using gRPC url: http://localhost:50055/. Retrying in 10s. Error: status: Unknown, message: "h2 protocol error: http2 error", details: [], metadata: MetadataMap { headers: {} }

Note: We have changed the localhost to machine IP but no luck
