### ISSUE TITLE
Unable to chain iptables command in pre_up

### ISSUE THREAD

**Issue by Netherwhal** [DefGuard/gateway#89]
```
defguard-gateway[22075]: [2024-03-24T16:40:21Z INFO  defguard_gateway] Executing specified PRE_UP command: iptables -A FORWARD -i wg0 -o eth0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
defguard-gateway[22075]: [2024-03-24T16:40:21Z ERROR defguard_gateway] Error executing command. Stderr:
defguard-gateway[22075]:     Bad argument `iptables'
defguard-gateway[22075]:     Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by teon** [comment]
doing commands with ";" one assumes that there is a shell execution (the ";" commands separator is a shell functionality). We do not use a shell.
If you would like to have multiple commands please create a script an then add this to pre/post:
`/path/tp/shell /path/to/script/as/argument`

**Comment by Netherwhal** [comment]
my bad, this was example config: https://github.com/DefGuard/gateway/blob/main/example-config.toml#L31

**Comment by teon** [comment]
Ok so it's our bug ;-) sorry about that! will correct the example

**Comment by teon** [comment]
Fixed the documentation.
