### ISSUE TITLE
Install package DefGuard on Opnsense , error "wrong architecture" 

### ISSUE THREAD

**Issue by Paulpatou** [DefGuard/gateway#92]
I'm trying to install the DefGuard plugin for OPNsense by following the documentation https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/gateway#package-install
, but I get the following error:
```

pkg: wrong architecture: Linux:6:x86:64 instead of FreeBSD:13:amd64
Failed to install the following 1 package(s)
```
I tested with two packages:
defguard-gateway_0.6.1_x86_64-unknown-freebsd.pkg
defguard-gateway_0.6.1_x86_64-unknown-opnsense.pkg

Here is the version of OPNsense that I use:
OPNsense 24.1.2_1-amd64
FreeBSD 13.2-RELEASE-p10

**Comment by teon** [comment]
Hi @Paulpatou - we are aware of this bug. Here is the original issue: https://github.com/DefGuard/deployment/issues/31
with the workaround: https://github.com/DefGuard/deployment/issues/31#issuecomment-1895415145

You can watch that one for proper fix.

Unfortunately GitHub Runner doesn't support FreeBSD - so we have no way of automating building proper packages with the current pipelines setup...
