### ISSUE TITLE
Frame with invalid size error

### ISSUE THREAD

**Issue by mmarin11** [DefGuard/gateway#95]
Hi Defguard community

I'm trying to configure an external gateway and I'm getting the following error. Has someone experimented a similar error when the gateways is in a different network/server? I double checked the firewall rules and it does not seem to be a connectivity problem

gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::proto::connection] Connection; peer=Client
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG tower::buffer::worker] service.ready=true message=processing request
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1) }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library)
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::codec::framed_write] send frame=GoAway { error_code: FRAME_SIZE_ERROR, last_stream_id: StreamId(0) }
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG h2::proto::connection] Connection::poll; connection error error=GoAway(b"", FRAME_SIZE_ERROR, Library)
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG hyper::proto::h2::client] connection error: connection error detected: frame with invalid size
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG hyper::client::service] connection error: hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) })
gateway-gateway-1  | [2024-04-26T05:39:57Z DEBUG hyper::proto::h2::client] client response error: connection error detected: frame with invalid size

**Comment by teon** [comment]
We have released a 0.7.1 gateway version that fixes the problem. If not please re-open and post more logs.
